### ISSUE TITLE
Possible memory leakage

### ISSUE THREAD

**Issue by jgerlach-erminas** [erminas/noderedrevpinodes-server#5] opened 2021-03-10 09:29 UTC
https://revolution.kunbus.de/forum/viewtopic.php?f=48&t=2482#p9857

User bigmanvstrashman reported a high RAM usage after 24h runtime.

**Comment by Putzeimer** [comment] 2021-03-12 16:52
I'm facing memory issues, too. The RevPi doesn't respond anymore after 2 days, so power off is the only way to bring it back up.
I'm not sure whether it occurs since I installed v1.0.3 or since the day I added the second DIO module.
I monitored the memory usage every hour since yesterday. The available memory decreases by about 20 to 25 MB every hour.

I've added my logfile for analysis purposes: [revpi-server.log.gz](https://github.com/erminas/noderedrevpinodes-server/files/6131523/revpi-server.log.gz)

Feel free to ask for further information.

**Comment by Putzeimer** [comment] 2021-03-22 17:07
Seems that there are more problems than this. Since server v1.0.3 and nodes v1.0.8, the revpi-single-input triggers randomly with wrong state. Not sure if the bug is in the nodes or the server, or if it is related to the memory leakage, so feel free to move the post to where it belongs.
I moved back to v1.0.1/v1.0.6-1 and the problems are gone.

**Comment by Putzeimer** [comment] 2021-05-08 18:22
I have to recall the statement "problems are gone", unfortunately.
Even with server 1.01 and nodes 1.0.6-1, the inputs trigger randomly. I replaced the RevPi with a box from one of your competitors (I call it "other"). Then, I wired all inputs to both boxes. Outputs are only connected to the other box, though. I then used the file node to log all incoming events from both boxes with node-red.
So, if a switch, connected to the inputs, ist turned on/off, both nodes (your's and the one from the other box) log a line in the logfile. So far so good. But very randomly, the RevPi logs an event when the other box does not. I'm pretty sure, the other box is right.

Here is an extraction from the logfile:
[2021-04-18T21:25:27.284Z] RevPi: Input 2, false
[2021-04-18T21:25:27.357Z] Other: Input 2, false
[2021-04-18T21:25:27.940Z] RevPi: Input 4, true
[2021-04-18T21:25:28.004Z] Other: Input 4, true
[2021-04-18T21:25:28.139Z] RevPi: Input 4, false
[2021-04-18T21:25:28.239Z] Other: Input 4, false
**[2021-04-19T17:05:15.493Z] RevPi: Input 4, true
[2021-04-19T17:05:15.919Z] RevPi: Input 4, false**
[2021-04-19T17:05:19.415Z] RevPi: Input 4, true
[2021-04-19T17:05:19.521Z] Other: Input 4, true
[2021-04-19T17:05:19.596Z] RevPi: Input 4, false
[2021-04-19T17:05:19.676Z] Other: Input 4, false
[2021-04-19T17:05:21.202Z] RevPi: Input 4, true
[2021-04-19T17:05:21.316Z] Other: Input 4, true

This is a very serious issue. Without fixing this, the RevPi DIO can't be used with node-red - especially not in an industrial environment. Think of an emergency shutdown button that randomly stops a whole production line.

I'm going to update the RevPi to buster, soon. I don't think that this issue will then be fixed, especially because you haven't even answered for more than 6 weeks, but hope dies last.
I'm looking forward in using the RevPi again, but I don't see any chance at the moment.

**Comment by Aurelog** [comment] 2021-08-24 13:40
Hello,
Got the same memory leak than described.
At start revpi-server.py uses only 2.1% but continue increasing to reach 39% after 32hrs.
Then revpi stop working after ~48hrs.

node-red-contrib-revpi-nodes 1.0.7-2

Currently trying a workaround using `sudo systemctl restart noderedrevpinodes-server.service` every day using crontab. In my use case 5s deadtime is ok.

If you need more information let me know

![RevPiServer_Mem_start](https://user-images.githubusercontent.com/42992071/130626939-7805587b-811e-4371-963a-2c59bd59ec07.PNG)
![RevPiServer_Mem_Leak](https://user-images.githubusercontent.com/42992071/130626941-a8717c3f-2ed4-4aef-9619-a3349650f42a.PNG)

**Comment by Misery42** [comment] 2021-09-08 16:34
Hello guys,
same here also Memory leak and revpi starts crashing.

Any ideas why?

**Comment by sklein-leogistics** [comment] 2021-09-09 08:47
Hello guys,
same here also Memory leak and revpi starts crashing.

Any ideas why?

**Comment by Aurelog** [comment] 2021-09-09 13:59
@sklein-leogistics i do not have any Dev feedback about this issue. I'll notify RevPi Dev on their forum.

By now, to avoid any crash i reset revpi-service every night :

```
sudo crontab -e

0 0 * * * systemctl restart noderedrevpinodes-server.service
```

**Comment by sklein-leogistics** [comment] 2021-09-10 16:54
Ich kann nur zur alternative revpupyload.py raten!
Ist zwar nicht so schön einfach wie mit dem NodeRED Nodes zu arbeiten aber mit MQTT als lokale Installation läufts und läufts und läufts....  315 Tage bis jetzt. Es wäre bestimmt schon über 900 aber vermutlich hatte der Kunde mal einen Stromausfall.

![image](https://user-images.githubusercontent.com/90382934/132889443-77ad63bc-0448-47a5-8365-aaa7d64c6367.png)

**Comment by sklein-leogistics** [comment] 2021-09-11 12:56
![image](https://user-images.githubusercontent.com/90382934/132948504-89204c82-9d30-477f-95c3-a35526f3c604.png)

![image](https://user-images.githubusercontent.com/90382934/132948509-f896da6b-61ff-45d6-8207-3cb11fa9b808.png)

How is this possible?

**Comment by sklein-leogistics** [comment] 2021-09-20 08:12
### **Hardware Monitoring:**
Die Speicher Problematik fällt nur auf dem CheckIn Terminal 101 auf.
Der Reset erfolgt alle 24h nachts um 00:00 Uhr bei ca. 66% Auslastung.
Ich Vermute das es damit zu tun hat das wir hier 2 DIO Module einsetzen was der einzige Unterschied zu sein scheint.
Ein Bug im revpi-server.py produziert dann einen Speicherüberlauf.

![MemTerminals](https://user-images.githubusercontent.com/90382934/133972890-b85908f9-01db-4357-a5c0-c4b4a57c642c.JPG)
### **Die Linux Releases:**
PC-TERM101 -> Linux Debian (buster)
PC-TERM351 -> Linux Debian (stretch)
PC-TERM352 -> Linux Debian (buster)

**Comment by Aurelog** [comment] 2021-10-11 11:46
@LuckyLukeCH @sklein-leogistics got a response from RevPi Team on revolutionpi support forum.
They are working on it. But no release date sheduled right now.

Link :
[https://revolutionpi.de/forum/viewtopic.php?f=6&t=3115](https://revolutionpi.de/forum/viewtopic.php?f=6&t=3115)

**Comment by LuckyLukeCH** [comment] 2021-10-11 12:46
Thank you Aurelog, but the "developers at the partner Erminas" are aware of it since 10. March this year and nothing happened...

For a product, which is sold as "industrial" this doesn't gain the convidence in the product, when "a partner company" is responsible but not running unter the priority system of the producer...

Regards from Switzerland
Lukas

**Comment by guidoffm** [comment] 2021-11-20 12:18
I have the same problem. Please fix it soon.

**Comment by LuckyLukeCH** [comment] 2021-11-20 12:32
Hello Guido,

The fix is working. You can apply it on the RevPi as root user with:
cd /usr/share/noderedrevpinodes-server/
git clone https://github.com/nbuchwitz/noderedrevpinodes-server.git
cd noderedrevpinodes-server/
git checkout bugfix/memleak-buster
cd ..
mv revpi-server.py revpi-server.old
cp noderedrevpinodes-server/revpi-server.py .
systemctl restart noderedrevpinodes-server.service

The original revpi-server is still there as revpi-server.old
We installed it in 3 systems already an there are no problems.

Regards from Switzerland,
Lukas Gaam

**Comment by guidoffm** [comment] 2021-11-20 14:54
Hi Lukas,
I have applied the fix. Let's see how it behaves. It took me so long to find out why the RevPi crashed each time after a few days. I then installed Prometheus node exporter and saw the memory consumption going up linearly with the time. 

Kind regards,
Guido

**Comment by guidoffm** [comment] 2021-11-22 13:55
The fix seems to work for me.

**Comment by meloni85** [comment] 2021-12-02 07:27
Hi all,
@sklein-leogistics and I also tested the new version with bug fix and it works fine (see picture).

![image](https://user-images.githubusercontent.com/78920479/144376701-dc19535f-9e59-44b0-a993-e03b1440c71f.png)

We were initially running the old version. Then, easy to guess, the new version was installed around 02/12 at 16:00.
By the way, those drops in RAM usage with the old version were occurring upon deploying an updated flow in node-red.

Best Regards,
Alessio

**Comment by meloni85** [comment] 2021-12-20 08:45
Unfortunately I have to retract the above statement. With the new version, it looks like we are not getting the inputs anymore (e.g. button pressed and nothing happens). I am currently trying to look into the issue and the changes that have been done in the way the coroutines are called. Am I the only one experiencing this issue?

**Comment by LuckyLukeCH** [comment] 2021-12-20 13:11
Hello Alessio,

We are not using the digital-inputs at the moment.
For the analog-inputs we are using the 'revpi-getpin', which is working.

Could you check, if there is a delay of 60s for the digital-inputs? This behavior I remember as well before we changed to 'revpi-getpin'...
Probably best would be to add a bug report to https://github.com/nbuchwitz/noderedrevpinodes-server

Regards Lukas Gaam

**Comment by meloni85** [comment] 2021-12-20 13:39
Hello Lukas,
thank you for your feedback. It looks like the problem occurs only with the revpi-single-input and revpi-multiple-input blocks and not with those triggered from nodered (i.e. getpin and output).

As you suggested I would open a new issue there but this option is not enabled in @nbuchwitz repository. Maybe @crismancich can help with that.

I have identify where the issue could be. But I'd like to be more extensive in the right place :)

**Comment by dfilsinger-erminas** [comment] 2022-03-08 10:33
Hello, 
we fixed this issue in the new server version 1.0.9. For this server you need also the new version of the nodes 1.0.3.
In the tests of the last two weeks we could not detect any memoryleak. 

Currently you can install the repositories directly. The server package for Debian and the update for npm will be released soon.

Regards Dennis

**Comment by meloni85** [comment] 2022-03-08 10:38
Hi Dennis,
you mean that also the problem with the "RevPi - single input" not working has been resolved? The last update was solving the issue with memoryleak but introduced some collateral issues.

Regards

Alessio

**Comment by dfilsinger-erminas** [comment] 2022-03-08 12:28
hi Allesio,
I don't know exactly what you mean by "RevPi - single input not working", but we have tested the new version and all nodes are working. 
There shouldn't be any collertaral damage issues by this fix.

Regards
Dennis

**Comment by meloni85** [comment] 2022-03-10 11:01
Hi Dennis,
could you please more specific about what you mean by "For this server you need also the new version of the nodes 1.0.9."? A link would be appreciated.

As to my previous message...
I meant that I tried out the forked version from @nbuchwitz and there was actually another problem there. Namely, that version would work fine only with Rpi nodes in nodered pulling DI status. The node "RevPi - single input not working" would hang and not trigger an event. Funny enough, when try to pull the status, all the hanging messages from that node are finally sent. I didn't go much in depth but it looked to be related to the way asyncio was managed.

Regards
Alessio

**Comment by dfilsinger-erminas** [comment] 2022-03-10 11:36
Hey Allesio,
 you can find the prerelease here [Nodes 1.0.9](https://github.com/erminas/node-red-contrib-revpi-nodes/releases/tag/1.0.9).

**Comment by meloni85** [comment] 2022-03-10 14:34
Hi Dennis,
I tried to install the new releases and the problem I have still occurs.
I am attaching a GIF to show you what I mean.
In short, you can see the node **RevPi - getpin** works fine. The node **revpi - single-input** instead does not return anything on status changes.

It is like that message is buffered and returned together with other messages when I trigger **RevPi - getpin**.

![DI_bug](https://user-images.githubusercontent.com/78920479/157676328-8c177ec6-09b4-40c5-86f0-d03f0a6faa9e.gif)

As said, I digged a bit into the content of the _revpi-server.py_ file and it looks to me like the problem comes from the use of the function asyncio.gather which waits for both retrieve and publish tasks to be completed. And that is the case only with **RevPi - getpin**. Thus the behavior in the GIF.

Regards
Alessio (single l, double s)

**Comment by dfilsinger-erminas** [comment] 2022-03-15 08:45
Hi Alessio, 
First of all, I am sorry about my mistake with your name.
After a little debug session, it looks like our fix disables the auto-send feature. This solves the memory leak problem, but it's more than just a collateral damage. For now, we are working on a solution and will keep you updated here.

Regards
Dennis

**Comment by LuckyLukeCH** [comment] 2022-03-15 09:10
Hello,

I can confirm the above behavior/bug and we reported this on 20.12.21...

Regards
Lukas Gaam

**Comment by meloni85** [comment] 2022-03-15 09:43
Hi Dennis,
I myself tried a modified version which seems to work and looks like does not lead to any memory leak. But I did not have time to test it yet and I would say it is kind of a quick fix.

Basically I got rid of all the part in bold. In other words, tasks are not executed explicitly with _asyncio.gather_ but rather left in the background to be executed in idle cycles. However, the presence of _await asyncio.sleep(0.1)_ actually ensures this moment comes at every while iteration.

```
            while self.running:

                retrieve_task = asyncio.ensure_future(self.get_client_requests(client, path))
                publish_task = asyncio.ensure_future(self.publish_messages_to_client(client, path))

                **tasks = [retrieve_task, publish_task]
                results = await asyncio.gather(*tasks, return_exceptions=True)
                # reraise gathered exceptions to find disconnected clients
                for result in results:
                  if isinstance(result, Exception):
                      raise result**
     
                await asyncio.sleep(0.1)
```

Hope this helps

Alessio

**Comment by dfilsinger-erminas** [comment] 2022-03-17 09:57
Hello, 
we have a stable version [here ](https://github.com/erminas/noderedrevpinodes-server/blob/962ead93be90f943c4d7973575f3c752c059f6d9/revpi-server.py) that we are currently testing. If everything still goes well, we will include these changes in the release next week. 

Regards 
Dennis

**Comment by ben-fussell** [comment] 2022-03-22 20:49
@dfilsinger-erminas are you still on track to release this week?

**Comment by dfilsinger-erminas** [comment] 2022-03-23 13:42
Hello, 
we have updated the release [1.0.3](https://github.com/erminas/noderedrevpinodes-server/releases/tag/1.0.3-2) now. It works with the Nodes version [1.0.9](https://github.com/erminas/node-red-contrib-revpi-nodes/releases/tag/1.0.9). You can install it manually as described in the readmes. The updates to install it via apt-get and npm will follow very soon.

Regards Dennis

**Comment by Putzeimer** [comment] 2022-03-23 14:18
Why not name it 1.0.4? 
1.0.3 has already been released a year ago.
It's very confusing to have different versions with the same version number.

**Comment by dfilsinger-erminas** [comment] 2022-03-23 18:15
Hey Putzeimer,
you're indeed right about that. I have reset the release 1.0.3 to the status from last week and published the current version in release1.0.4.

Regards 
Dennis

**Closed** 2022-03-28 07:25 UTC
Labels: bug
